---
- name: Create a VPC with its requirements
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Create the AWS VPC
      amazon.aws.ec2_vpc_net:
        name: VPCLCL42837_FIRST
        cidr_block: 10.0.0.0/20
        region: us-west-2
      register: aws_vpc_info

    - name: Set a cacheable fact
      ansible.builtin.set_fact:
        vpc_info: "{{ aws_vpc_info }}"
      cacheable: yes

#    - name: Create the VPC Subnet
#      amazon.aws.ec2_vpc_subnet:
#        cidr: 10.0.0.0/24
#        region: us-west-2
#        az: us-west-2a
#        vpc_id: "{{ aws_vpc_info.vpc.id }}"
#    - name: Create the VPC Subnet
#      amazon.aws.ec2_vpc_subnet:
#        cidr: 10.0.0.0/24
#        region: us-west-2
#        az: us-west-2a
#        vpc_id: "{{ aws_vpc_info.vpc.id }}"
#    - name: Create the VPC Subnet
#      amazon.aws.ec2_vpc_subnet:
#        cidr: 10.0.0.0/24
#        region: us-west-2
#        az: us-west-2a
#        vpc_id: "{{ aws_vpc_info.vpc.id }}"
#    - name: Create the VPC Subnet
#      amazon.aws.ec2_vpc_subnet:
#        cidr: 10.0.0.0/24
#        region: us-west-2
#        az: us-west-2a
#        vpc_id: "{{ aws_vpc_info.vpc.id }}"
#    - name: Create the VPC Subnet
#      amazon.aws.ec2_vpc_subnet:
#        cidr: 10.0.0.0/24
#        region: us-west-2
#        az: us-west-2a
#        vpc_id: "{{ aws_vpc_info.vpc.id }}"
#    - name: Create the VPC Subnet
#      amazon.aws.ec2_vpc_subnet:
#        cidr: 10.0.0.0/24
#        region: us-west-2
#        az: us-west-2a
#        vpc_id: "{{ aws_vpc_info.vpc.id }}"






