---
- name: Create a VPC with its requirements
  hosts: localhost
  tasks:
    - name: Create the AWS VPC
      amazon.aws.ec2_vpc_net:
        name: VPCLCL42837_FIRST
        cidr_block: 10.0.0.0/20
        region: us-west-2
      register: vpc_info
    - name: VPC Public Subnet in AZ1
      amazon.aws.ec2_vpc_subnet:
        cidr: 10.0.0.0/24
        region: us-west-2
        az: us-west-2a
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: BUILD00001
      register: subnet_info1
    - name: VPC Private Subnet in AZ1
      amazon.aws.ec2_vpc_subnet:
        cidr: 10.0.1.0/24
        region: us-west-2
        az: us-west-2a
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: DEPLOY00001
      register: subnet_info11
    - name: VPC Public Subnet in AZ2
      amazon.aws.ec2_vpc_subnet:
        cidr: 10.0.2.0/24
        region: us-west-2
        az: us-west-2b
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: BUILD00011
      register: subnet_info2
    - name: VPC Private Subnet in AZ2
      amazon.aws.ec2_vpc_subnet:
        cidr: 10.0.3.0/24
        region: us-west-2
        az: us-west-2b
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: DEPLOY00011
      register: subnet_info12
    - name: Create VPC INTERNET GATEWAY
      ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpc.id }}"
        region: us-west-2
        tags:
          Name: VPCLCL42837_FIRST_IGW
      register: igw_info
    - name: Create Route table
      amazon.aws.ec2_vpc_route_table:
        region: us-west-2
        subnets:
          - "{{ subnet_info1.subnet.id }}"
          - "{{ subnet_info2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_info.gateway_id }}"
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: VPCLCL42837_FIRST_RT
    - name: Create Route table
      amazon.aws.ec2_vpc_route_table:
        region: us-west-2
        subnets:
          - "{{ subnet_info11.subnet.id }}"
          - "{{ subnet_info12.subnet.id }}"
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: VPCLCL42837_FIRST_RT
    - name: Create a Security Group
      amazon.aws.ec2_group:
        name: VPCLCL42837_FIRST_GRP
        description: SSH and HTTP access
        vpc_id: "{{ vpc_info.vpc.id }}"
        region: us-west-2
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
            cidr_ip: 0.0.0.0/0










