---
- name: Bulid Java Application
  hosts: build
  become: true
  vars:
    packages:
      - git
      - java-17*
      - maven
      - pip
  tasks:
    - name: Install necessary Components
      yum:
        state: present
        name: "{{ packages }}"
    - name: Get Application Code
      git:
        repo: 'https://github.com/CeeyIT-Solutions/JavaWeb3.git'
        dest: /home/ec2-user/JavaWeb3
        force: yes
    - name: Ensure Maven compiler plugin configuration block
      lineinfile:
        path: /home/ec2-user/JavaWeb3/pom.xml
        line: |
          <build>
              <plugins>
                  <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-compiler-plugin</artifactId>
                      <version>3.5.1</version>
                      <configuration>
                          <source>1.8</source>
                          <target>1.8</target>
                      </configuration>
                  </plugin>
                  <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-war-plugin</artifactId>
                      <version>3.3.2</version>
                  </plugin>
              </plugins>
          </build>
        insertafter: "</dependencies>"
        create: yes
      register: done
    - name: test compile and build the application
      shell: |
        cd JavaWeb3
        sudo mvn clean test compile package
      when: done.changed
#    - name: check
#      file:
#        path: /home/ec2-user/JavaWeb3/target/WebAppCal-0.0.6.war
#        state: touch
    - name: Save the Target file to local host
      ansible.builtin.fetch:
        src: /home/ec2-user/JavaWeb3/target/WebAppCal-0.0.6.war
        dest: /home/ec2-user/
        flat: true

    #    - name: Set Maven Compiler Plugin configuration
    #      xml:
    #    - name: Ensure Maven compiler plugin configuration block
    #      blockinfile:
    #    - name: Install lxml Python library on target hosts
    #      ansible.builtin.pip:
    #
