---
- name: Setup Apache Tomcat
  hosts: deployServer1
  become: true
  vars:
    packages:
      - java-1.8*
      - wget
  tasks:
    - name: Install Necessary Dependencies
      yum:
        state: present
        name:  "{{ packages }}"
    - name: Download and Extract Tomcat Binary
      shell: |
        if [ ! -d apache-tomcat-7.0.94 ]; then
          wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
          tar xvf apache-tomcat-7.0.94.tar.gz
          rm -fr apache-tomcat-7.0.94.tar.gz
        fi
    - name: Startup the Server
      shell: |
        cd apache-tomcat-7.0.94
        cd bin 
        ./startup.sh
    - name: Copy the aws credential files to target host
      copy:
        src: /home/ec2-user/.aws/credentials
        dest: /home/ec2-user/.aws/
    - name: Copy the aws config files to target host
      copy:
        src: /home/ec2-user/.aws/config
        dest: /home/ec2-user/.aws/
    - name: Download files from S3 Bucket to Deploy Server
      shell: |
        aws s3 cp s3://prjwarfilebck001/WebAppCal-0.0.6.war home/ec2-user/apache-tomcat-7.0.94/webapps
      become_user: ec2-user
        
    
        
