[build]
b1 ansible_host=10.0.0.130 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/tochekey.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
b2 ansible_host=10.0.2.158 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/tochekey.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
;
; [deployment]
; d1 ansible_host=172.31.84.12 ansible_user=ubuntu ansible_ssh_private_key_file=/home/centos/toche1.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' apache_package=apache2
; d2 ansible_host=172.31.82.183 ansible_user=ec2-user ansible_ssh_private_key_file=/home/centos/toche1.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' apache_package=httpd

[local]
localhost ansible_connection=local